// Mocks generated by Mockito 5.0.17 from annotations
// in flutter_graphql/test/future/product/infrastructure/repository/product_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_graphql/core/network/network_info.dart' as _i5;
import 'package:flutter_graphql/futures/product/domain/domain.dart' as _i4;
import 'package:flutter_graphql/futures/product/infrastrucure/datasource/product_remote_data.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ProductRemoteData].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteData extends _i1.Mock implements _i2.ProductRemoteData {
  MockProductRemoteData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Product>> getProduct() =>
      (super.noSuchMethod(Invocation.method(#getProduct, []),
              returnValue: Future<List<_i4.Product>>.value(<_i4.Product>[]))
          as _i3.Future<List<_i4.Product>>);
}

/// A class which mocks [NetWorkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetWorkInfo extends _i1.Mock implements _i5.NetWorkInfo {
  MockNetWorkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
